---

- name: Update apt repository cache
  apt: update_cache=yes

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['curl', 'vim', 'git', 'ufw', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'python3-setuptools']

- name: Downloading docker installer
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '777'

- name: Installing docker
  shell: "sh /tmp/get-docker.sh"

- name: Ensuring docker command is on path
  shell: "docker -v"

- name: Add users to "docker" group
  user:
    name: "{{ item.name }}"
    groups: docker
    append: yes
  with_items: "{{ users }}"

- name: Install Docker Compose module for Python
  pip:
    name: docker-compose
    version: "{{ docker_compose_version }}"
    state: present

- name: Ensuring docker-compose command is on path
  shell: "sudo docker-compose -v"

